### PR TITLE
28 chart for comparison

### PR DESCRIPTION
**Pull request by masterYoda8**

### CODE REVIEW

**Review by xgsngxguy — APPROVED** [review]
iO!

**Review by fabibec — APPROVED** [review]
LGTM

**Review by xgsngxguy — CHANGES_REQUESTED** [review]
I will add another approach later on.

**Comment by xgsngxguy** [comment]
@masterYoda8 what do you think about this approach?

**Review by xgsngxguy — APPROVED** [review]

**Pull request merged**
